# Project information
site_name: 'thg-framework'
site_description: 'thg full docs'
site_author: 'darkcode0x00 luizcorrea'
site_url: 'https://darkcode357.github.io/thg-framework/'
# Repository
repo_name: 'darkcode357/thg-framework'
repo_url: 'https://github.com/darkcode357/thg-framework'
# Copyright
copyright: 'Copyright &copy; 2019 - 2020 darkcode0x00'
# Configuration
theme:
  name: 'cyborg'
# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'
#exx
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

plugins:
  - search
nav:
- Overview:
  - Installation: ./cli/install.md
  - Introduction: index.md
  - Community: community.md
  - Conceptual: conceptual.md
  - build: cli/build.md
  - tags: cli/tags.md
  - LICENSE: ./LICENSE.md

- Contributing:
  - Get Started: ./contributing/Contributing-to-thg.md
  - templates: cli/templates.md

- documentation:
  - capture the flag:
    - basic:
      - analysis:
        - linux: ./capturetheflag/basic/analysis/linux.md
        - windows: ./capturetheflag/basic/analysis/windows.md
        - malware: ./capturetheflag/basic/analysis/malware.md
      - recovery:
        - backup: ./capturetheflag/basic/recover/backuo.md
        - patching: ./capturetheflag/basic/recover/patching.md
      - tips_end_tricks:
        - tools: ./capturetheflag/basic/tips_end_tricks/tools.md
        - decoding: ./capturetheflag/basic/tips_end_tricks/decoding.md
        - dos: ./capturetheflag/basic/tips_end_tricks/dos.md
        - os_cheats: ./capturetheflag/basic/tips_end_tricks/os_cheats.md
        - snort: ./capturetheflag/basic/tips_end_tricks/snort.md
      - identify:
        - basic: ./capturetheflag/basic/identify/basic.md
        - nmap: ./capturetheflag/basic/identify/nmap.md
        - nessus: ./capturetheflag/basic/identify/nessus.md
        - openvas: ./capturetheflag/basic/identify/openvas.md
        - windows: ./capturetheflag/basic/identify/windows.md
        - linux: ./capturetheflag/basic/identify/linux.md
      - defend:
        - windows: ./capturetheflag/basic/prootect_defend/windows.md
        - linux: ./capturetheflag/basic/prootect_defend/linux.md
      - identify:
        - tcpdump: ./capturetheflag/basic/detect/tcpdump.md
        - edicap: ./capturetheflag/basic/detect/editcap.md
        - mergecap: ./capturetheflag/basic/detect/mergecap.md
        - snort: ./capturetheflag/basic/detect/snort.md
        - tshark: ./capturetheflag/basic/detect/tshark.md
        - analysis: ./capturetheflag/basic/detect/analysis.md
        - os:
          - linux: ./capturetheflag/basic/detect/linux.md
          - windows: ./capturetheflag/basic/detect/windows.md
      - Deployment: deployment.md
    - hash_crack:
        - index: ./capturetheflag/hash_crack/index.md
        - CORE_HASH_CRACKING_KNOWLEDGE: ./capturetheflag/hash_crack/CORE_HASH_CRACKING_KNOWLEDGE.md
  - pentest_standard:
    - Pre engagement Interactions: ./pentest_standard/preengagemente.md
    - Intelligence Gathering: ./pentest_standard/ig.md
    - Threat Modeling: ./pentest_standard/threatmodeling.md
    - Vulnerability Analysis: ./pentest_standard/vulnterability.md
    - Exploitation: ./pentest_standard/exploration.md
    - Post Exploitation: ./pentest_standard/postexploration.md
    - Reporting: ./pentest_standard/report.md
    - Technical Guidelines: ./pentest_standard/tecguidelines.md
- CLI:
  - THG-PART-1:
    - THG: ./tutorials/thg.md
    - thg_server: ./tutorials/server/server.md
    - thg_version: ./tutorials/version/version.md
    - thg_shells: ./tutorials/shells/shells.md
    - thg_docs:  ./tutorials/thg_docs/thg_docs.md
    - thg_auxiliares: ./tutorials/auxiliares/auxiliares.md
    - thg_anti_forensic: ./tutorials/anti_forensic/anti_forensic.md
    - thg_crypto: ./tutorials/crypto/crypto.md
    - thg_drone: ./tutorials/drone/drone.md
    - thg_keylogger: ./tutorials/keylogger/keylogger.md
    - thg_recon: ./tutorials/recon/recon.md
    - thg_voip: ./tutorials/voip/voip.md
    - thg_automation: ./tutorials/automation/automation.md
    - thg_cryptography: ./tutorials/cryptography/cryptography.md
    - thg_exploitation: ./tutorials/exploitation/exploitation.md
    - thg_malware: ./tutorials/malware/malware.md
    - thg_reversing: ./tutorials/reversing/reversing.md
    - thg_windows: ./tutorials/thg_windows/thg_windows.md
    - thg_automobile: ./tutorials/automobile/automobile.md
    - thg_database: ./tutorials/database/database.md
    - thg_fingerprint: ./tutorials/fingerprint/fingerprint.md
    - thg_misc: ./tutorials/misc/misc.md
    - thg_sniffer: ./tutorials/sniffer/sniffer.md
    - thg_wireless: ./tutorials/wireless/wireless.md
    - thg_debugger: ./tutorials/debugger/debugger.md
    - thg_firmware: ./tutorials/firmware/firmware.md
    - thg_mobile: ./tutorials/mobile/mobile.md
    - thg_social: ./tutorials/social/social.md
    - thg_backdoor: ./tutorials/backdoor/backdoor.md
    - thg_decompiler: ./tutorials/decompiler/decompiler.md
    - thg_forensic: ./tutorials/forensic/forensic.md
  - THG-PART-2:
    - thg_networking: ./tutorials/networking/networking.md
    - thg_spoff: ./tutorials/spoff/spoff.md
    - thg_binary: ./tutorials/binary/binary.md
    - thg_defensensive: ./tutorials/defensensive/defensensive.md
    - thg_gpu: ./tutorials/gpu/gpu.md
    - thg_os: ./tutorials/os/os.md
    - thg_nfc: ./tutorials/nfc/nfc.md
    - thg_spoof: ./tutorials/spoof/spoof.md
    - thg_version: ./tutorials/version/version.md
    - thg_bluetooth: ./tutorials/bluetooth/bluetooth.md
    - thg_defensive: ./tutorials/defensive/defensive.md
    - thg_hardware: ./tutorials/hardware/hardware.md
    - thg_packer: ./tutorials/packer/packer.md
    - thg_stego: ./tutorials/stego/stego.md
    - thg_code_audit: ./tutorials/code_audit/code_audit.md
    - thg_disassembler: ./tutorials/disassembler/disassembler.md
    - thg_honeypot: ./tutorials/honeypot/honeypot.md
    - thg_proxy: ./tutorials/proxy/proxy.md
    - thg_tunnel: ./tutorials/tunnel/tunnel.md
    - thg_cracker: ./tutorials/cracker/cracker.md
    - thg_dos: ./tutorials/dos/dos.md
    - thg_ids: ./tutorials/ids/ids.md
    - thg_radio: ./tutorials/radio/radio.md
    - thg_unpacker: ./tutorials/unpacker/unpacker.md


